baseURL: "yashtrivedi.netlify.app"
languageCode: en-us
title: Yash Trivedi
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    #- identifier: blog
     # name: Blog
      #url: /blog
      #weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    #- identifier: notes
      #name: Notes
      #url: https://notes.arkalim.org
     #weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Yash Trivedi"
    subtitle: Computer Vision Research Intern @ DeepLearning and Computer Vision Lab of Zayed University Dubai [(link)](https://www.zu.ac.ae/main/en/)
    imageUrl: "home/me.jpg"
    imageWidth: 300
    imageHeight: 300
    # buttons:
    #   - name: Resume
    #     url: "https://drive.google.com/file/d/15bupi_Ez5GhhNa2LIT7an1Qxg-0XKYH2/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:yashtrivedi532@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/yash-trivedi-898004160/"
    - name: "github"
      url: "https://github.com/yashcoder007"
    #- name: "youtube"
      #url: "https://www.youtube.com/c/AbdurRahmanKalim"
    - name: "cv"
      url: 

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
